In [2]:
print("Hello world")
print("Sindhu")

Hello world
Sindhu


In [3]:
Print("hello")

NameError: name 'Print' is not defined

In [4]:
print('hello')

hello


In [5]:
print(hello)

NameError: name 'hello' is not defined

In [7]:
print(10)

10


###text->single or double inverted comma

### Data types

In [9]:
a=16
type(a)

int

In [10]:
b=12.4
type(b)

float

In [11]:
c=True
type(c)

bool

In [12]:
f=False
type(c)

bool

In [14]:
s="hello"
type(s)

str

# Rules for naming of variable

### vaiable name without white spaces
### variable names Shouldnot start with numbers
### speciacharaters ,operators are not allowed in variable names except _(underscore) only.
### case sensitive

In [15]:
courses="Ai","ml","datascience","web dev"
courses

('Ai', 'ml', 'datascience', 'web dev')

In [16]:
course names="Ai","web","python"
course names

SyntaxError: invalid syntax (1994128012.py, line 1)

In [17]:
3courses="python","web dev","datascience"
3courses

SyntaxError: invalid syntax (1591951048.py, line 1)

In [18]:
mycourses1="ml","web dev","python","java"
mycourses1

('ml', 'web dev', 'python', 'java')

In [19]:
choice='pen','paper','pencil'
choice

('pen', 'paper', 'pencil')

In [21]:
choice='pen','paper',"pencil",10
choice

('pen', 'paper', 'pencil', 10)

In [22]:
cho+ice='pen','paper','pencil'
cho+ice

SyntaxError: cannot assign to operator (995507786.py, line 1)

In [23]:
cho!ice='pen','paper','pencil'
cho!ice

SyntaxError: invalid syntax (1314012504.py, line 1)

In [24]:
_courses="Ai","Ml","webdev"
_courses

('Ai', 'Ml', 'webdev')

### Numpy

In [3]:
import numpy as np

In [4]:
my_list=[23,45,6,4]
np.array(my_list)

array([23, 45,  6,  4])

In [5]:
mat=[[1,2,3],[4,5,6],[5,6,7]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [6]:
np.arange(1.5,56.7)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
       12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5,
       23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5,
       34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5,
       45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5, 55.5,
       56.5])

In [7]:
np.arange(2.34,5.64)

array([2.34, 3.34, 4.34, 5.34])

In [8]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(3,int)

array([0, 0, 0])

In [14]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:

np.ones(2,int)

array([1, 1])

In [21]:
#uniform values
np.random.rand(1,56,3)


array([[[0.85697554, 0.75371299, 0.35512925],
        [0.15577599, 0.03704958, 0.11275003],
        [0.81662298, 0.37240323, 0.3189481 ],
        [0.81049166, 0.774459  , 0.40090967],
        [0.55101296, 0.10267035, 0.71547549],
        [0.98038999, 0.66275854, 0.61037328],
        [0.83391491, 0.53738908, 0.81394657],
        [0.25919624, 0.84615043, 0.7380813 ],
        [0.86212531, 0.91530207, 0.82603382],
        [0.16721709, 0.17064289, 0.34047656],
        [0.71721382, 0.7398321 , 0.0961713 ],
        [0.6305871 , 0.9116293 , 0.39677943],
        [0.8209543 , 0.39983133, 0.79561967],
        [0.81543162, 0.40660807, 0.92592759],
        [0.70771713, 0.79833528, 0.29801707],
        [0.3986832 , 0.32752489, 0.90369058],
        [0.05628984, 0.70098587, 0.41687681],
        [0.79807555, 0.62381292, 0.26887499],
        [0.19473601, 0.21912971, 0.5792845 ],
        [0.46435926, 0.37104457, 0.88821871],
        [0.38141691, 0.46590591, 0.43990458],
        [0.57042791, 0.17011292, 0

In [5]:
np.random.randn(1,5,2)

array([[[-1.02288645,  0.05479492],
        [ 1.13555251, -0.37422762],
        [ 0.97197272,  0.48841238],
        [-0.7514861 , -1.62574683],
        [ 0.68767239, -0.64224716]]])

In [15]:
np.random.randint(20,56,100)

array([50, 20, 41, 35, 37, 53, 32, 37, 52, 48, 38, 35, 35, 38, 55, 24, 37,
       25, 34, 26, 25, 54, 33, 34, 21, 49, 46, 53, 30, 23, 36, 39, 23, 55,
       46, 55, 37, 42, 21, 39, 45, 49, 37, 26, 23, 40, 24, 29, 31, 25, 54,
       39, 24, 32, 37, 41, 20, 48, 29, 39, 37, 54, 33, 53, 44, 30, 20, 36,
       49, 33, 21, 50, 25, 42, 49, 30, 50, 39, 20, 36, 49, 31, 40, 31, 21,
       40, 39, 24, 41, 53, 24, 28, 41, 32, 53, 28, 47, 29, 48, 38])

In [19]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [11]:
rand_array=np.random.randint(0,100,20)
rand_array

array([63, 64, 52, 48, 20, 25, 98, 57, 45, 68, 67,  8, 53, 38, 47, 31, 88,
       37, 77, 50])

In [12]:
rand_array.min()

8

In [14]:
rand_array.argmin()

11

In [15]:
sample_array.dtype

dtype('int32')

In [16]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
sample_array[3:7]

array([3, 4, 5, 6])

In [5]:
sample_array[4:10]=100
sample_array

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [6]:
sample_array[0:7]

array([  0,   1,   2,   3, 100, 100, 100])

In [7]:
subset_array=sample_array[0:7]
subset_array

array([  0,   1,   2,   3, 100, 100, 100])

In [8]:
subset_array[1:4]=1001
subset_array

array([   0, 1001, 1001, 1001,  100,  100,  100])

In [9]:
subset_array[:]=125
subset_array

array([125, 125, 125, 125, 125, 125, 125])

### TwoDimentional array

In [11]:
matrix=np.array(([1,2,3],[4,5,6],[7,8,9]))
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matrix[0][2]

3

In [12]:
matrix[2:]

array([[7, 8, 9]])

In [14]:
matrix[2]

array([7, 8, 9])

In [16]:
matrix[:,(2,1)]

array([[3, 2],
       [6, 5],
       [9, 8]])

### Selection Techniques

In [20]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [20]:
#exponential 
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [21]:
#sqrt
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [22]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [21]:
np.std(sample_array)

5.477225575051661

In [23]:
np.max(sample_array)

19

In [24]:
np.min(sample_array)

1

In [25]:
np.mean(sample_array)

10.0

In [27]:
array=np.random.randn(3,4)
array

array([[ 0.08814505, -1.33604648,  0.50288988,  0.3702438 ],
       [-1.31304753,  0.30843723,  0.07438463, -0.50994166],
       [-1.06804696,  0.3672791 , -0.10560544,  0.29350438]])

In [28]:
np.round(array,decimals=3)

array([[ 0.088, -1.336,  0.503,  0.37 ],
       [-1.313,  0.308,  0.074, -0.51 ],
       [-1.068,  0.367, -0.106,  0.294]])

In [29]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### Pandas

In [16]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/HHE_June5/main/CardioGoodFitness-1.csv")
df

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0     TM195   18    Male         14        Single      3        4   29562   
1     TM195   19    Male         15        Single      2        3   31836   
2     TM195   19  Female         14     Partnered      4        3   30699   
3     TM195   19    Male         12        Single      3        3   32973   
4     TM195   20    Male         13     Partnered      4        2   35247   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [18]:
df.shape

(180, 9)

In [29]:
df.head(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [16]:
df.tail(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
170   TM798   31    Male         16     Partnered      6        5   89641   
171   TM798   33  Female         18     Partnered      4        5   95866   
172   TM798   34    Male         16        Single      5        5   92131   
173   TM798   35    Male         16     Partnered      4        5   92131   
174   TM798   38    Male         18     Partnered      5        5  104581   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
170    260  
171    200  
172    150  
173    360  
174    150  
175    200  
176    200  
177    160  
178    120  
179    180

In [17]:
df.sample(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
163   TM798   28    Male         18     Partnered      7        5   77191   
102   TM498   25  Female         14        Single      2        3   43206   
126   TM498   34    Male         16     Partnered      3        4   59124   
173   TM798   35    Male         16     Partnered      4        5   92131   
80    TM498   19    Male         14        Single      3        3   31836   
179   TM798   48    Male         18     Partnered      4        5   95508   
28    TM195   25    Male         14     Partnered      2        3   45480   
165   TM798   29    Male         18        Single      5        5   52290   
0     TM195   18    Male         14        Single      3        4   29562   
37    TM195   26    Male         16     Partnered      3        3   51165   

     Miles  
163    180  
102     64  
126     85  
173    360  
80      64  
179    180  
28      56  
165    180  
0      112  
37      85

In [22]:
df.shape

(180, 9)

In [23]:
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [25]:
df.isnull().sum()

Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [31]:
df1=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/hotel_bookings.csv")
df1

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
0                          0       2  ...    No Deposit    NaN     NaN   
1                          0       2  ...    No Deposit    NaN     NaN   
2                          1       1  ...    No Deposit    NaN     NaN   
3                          1       1  ...    No Deposit  304.0     NaN   
4                          2       2  ...    No Deposit  240.0     NaN   
...                      ...     ...  ...           ...    ...     ...   
119385                     5       2  ...    No Deposit  394.0     NaN   
119386                     5       3  ...    No Deposit    9.0     NaN   
119387                     5       2  ...    No Deposit    9.0     NaN   
119388                     5       2  ...    No Deposit   89.0     NaN   
119389                     7       2  ...    No Deposit    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
0                         0     Transient    0.00   
1                         0     Transient    0.00   
2                         0     Transient   75.00   
3                         0     Transient   75.00   
4                         0     Transient   98.00   
...                     ...           ...     ...   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3             

In [32]:
df.isnull().sum()


Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [ ]:
## Pandas Series(uni dimentional data)

In [1]:
import numpy as np;
import pandas as pd;

In [29]:
label=['a','b','c','d','e']
sample_list=[100,200,340,560,567]
array=np.array([12,34,56,45,67])
dict={'w':10,'x':20,'z':40}

In [6]:
pd.Series(data=label)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [11]:
pd.Series(data=sample_list)

0    100
1    200
2    340
3    560
dtype: int64

In [8]:
pd.Series(array)

0    1
1    2
2    3
3    4
dtype: int32

In [9]:
pd.Series(data=dict)

w    10
x    20
z    40
dtype: int64

In [13]:
pd.Series(data=sample_list,index=label)

a    100
b    200
c    340
d    560
e    567
dtype: int64

In [30]:
pd.Series(array,label)

a    12
b    34
c    56
d    45
e    67
dtype: int32

### Pandas Dataframe and Indexing

In [31]:
sports1=pd.Series([2,3,6,7],index=['one','two','three','four'])
sports1

one      2
two      3
three    6
four     7
dtype: int64

In [32]:
sports1['three']

6

In [33]:
sports2=pd.Series([12,34,23,24],index=['one','two','three','four'])
sports2

one      12
two      34
three    23
four     24
dtype: int64

In [34]:
sports1+sports2

one      14
two      37
three    29
four     31
dtype: int64

In [20]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.480489  0.960569  0.398388  0.195531  0.154347
B  0.491239  0.284799  0.764484  0.231694  0.789401
C  0.078564  0.686359  0.852746  0.535688  0.897096
D  0.979241  0.201716  0.663258  0.264856  0.310714
E  0.419267  0.652216  0.339070  0.405778  0.692901
F  0.951358  0.201873  0.664589  0.017555  0.651172
G  0.675008  0.542411  0.476950  0.344626  0.635212
H  0.928990  0.120553  0.393359  0.116645  0.054980

In [24]:
df1['Score1']

A    0.480489
B    0.491239
C    0.078564
D    0.979241
E    0.419267
F    0.951358
G    0.675008
H    0.928990
Name: Score1, dtype: float64

In [25]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.480489  0.960569  0.398388
B  0.491239  0.284799  0.764484
C  0.078564  0.686359  0.852746
D  0.979241  0.201716  0.663258
E  0.419267  0.652216  0.339070
F  0.951358  0.201873  0.664589
G  0.675008  0.542411  0.476950
H  0.928990  0.120553  0.393359

In [29]:
df1['Score6']=df1['Score1']+df1['Score2'] 
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.480489  0.960569  0.398388  0.195531  0.154347  1.441058
B  0.491239  0.284799  0.764484  0.231694  0.789401  0.776038
C  0.078564  0.686359  0.852746  0.535688  0.897096  0.764923
D  0.979241  0.201716  0.663258  0.264856  0.310714  1.180957
E  0.419267  0.652216  0.339070  0.405778  0.692901  1.071483
F  0.951358  0.201873  0.664589  0.017555  0.651172  1.153231
G  0.675008  0.542411  0.476950  0.344626  0.635212  1.217419
H  0.928990  0.120553  0.393359  0.116645  0.054980  1.049543

In [30]:
dt={'Id':['101','102','103','104','105'],'name':['one','two','three','four','five']}
df=pd.DataFrame(dt)
df

Id   name
0  101    one
1  102    two
2  103  three
3  104   four
4  105   five

In [31]:
df['Id']

0    101
1    102
2    103
3    104
4    105
Name: Id, dtype: object

In [32]:
df[['Id','name']]

Id   name
0  101    one
1  102    two
2  103  three
3  104   four
4  105   five

In [33]:
df.drop('Id',axis=1)


name
0    one
1    two
2  three
3   four
4   five

In [41]:
df.drop(2)

Id  name
0  101   one
1  102   two
3  104  four
4  105  five